[workspace]
members = ["secure-login", "session-service"]
resolver = "2"

[package]
name = "p99-mobile-client"
version = "1.1.0"
description = "Project 1999 mobile chat client"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "p99_mobile_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.40", features = ["bundled", "serialize"] }
tempfile = "3"
url = "2"
uuid = { version = "1", features = ["v4"] }
tauri-plugin-opener = "2"
tauri-plugin-secure-login = { path = "secure-login" }
tauri-plugin-session-service = { path = "session-service" }
p99-logger-client = { git = "https://github.com/rm-you/p99-logger-client", branch = "main", default-features = false }


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
